### ISSUE TITLE
Informieren über eine mögliche Anbindung an Game Center

### ISSUE THREAD

**Issue by TobiasGit** [Simongotnews/SWP2#10]
AZ: 3 Personen à 20h.    Es soll sich informiert werden, wie man sich mit dem Game Center verbindet im Prototyp
Tatsächlich benötigte Zeit: 54:47

**Comment by Simongotnews** [comment]
Anbindung erfolgt über Leatherboards. Diese in XCode einfach einbinden und diverse Funktionen benutzen...
