### ISSUE TITLE
Stallgeflüsterartikel verfassen (inkl. Screenshot, Teamfoto, ca. 1 Seite DINA4)

### ISSUE THREAD

**Issue by Simongotnews** [Simongotnews/SWP2#101]

**Comment by SimoneAtSWP2** [comment]
4 h

**Comment by SimoneAtSWP2** [comment]
Teamfoto am Montag machen und Screenshot Game Scene wenn Game fertig, sonst fertig

**Comment by SimoneAtSWP2** [comment]
Teamfoto wurde von Prof. Wanner gemacht, Simone und Patrick machen Screenshot von Game Center, wenn Spiel dort akzeptiert wurde
