### ISSUE TITLE
Dummy gegen Bilder tauschen und Animation der Männchen beim werfen implementieren

### ISSUE THREAD

**Issue by Simongotnews** [Simongotnews/SWP2#22]
AZ: 8h p.P.

**Comment by Simongotnews** [comment]
30% Fertig
// Bilder überarbeitet. Einfügen kommt heute Nachmittag/Abend dran...

**Comment by Simongotnews** [comment]
#22 ca. 60% abgeschlossen (Sonntag 19:00)

**Comment by LeDaspien** [comment]
#22 ca. 80% abgeschlossen (Mittwoch 21:00)

**Comment by Simongotnews** [comment]
#22 90%, Merge steht noch bevor
