### ISSUE TITLE
Nach Rückkehr aus Kampfansicht: Statistik und Truppenwerte aktualisieren

### ISSUE THREAD

**Issue by Simongotnews** [Simongotnews/SWP2#44]
AZ: 2x 1,5 h
Nach der Rückkehr aus der GameScene in die GermanMap sollen die Truppenstärken der im Angriff beteiligten Bundesländer aktualisiert werden.
Auf der Deutschlandkarte sollen also die neuen Zahlen der Truppenstärke angezeigt werden.
Außerdem muss sichergestellt sein, dass die Statistiktabelle an die neuen angepasst wird.

**Comment by TetianaProkhorova** [comment]
Auf der Deutschlandkarte kann die Truppenstärke nicht aktualisiert werden, weil die Verschiebungsansicht-Szene noch nicht implementiert ist.

**Comment by TetianaProkhorova** [comment]
25% fertig

**Comment by TetianaProkhorova** [comment]
100% fertig
