### ISSUE TITLE
Schadenwerte überarbeiten (Kampfansicht)

### ISSUE THREAD

**Issue by Simongotnews** [Simongotnews/SWP2#45]
AZ: 3 St.
Momentan entsteht bei einer Kollision immer ein Schaden von 50. Dieser soll überarbeitet werden, sodass der Schaden aus der GermanMap in die GameScene übergeben wird. Die Höhe des Schadens soll sich dabei jeweils nach der Truppenanzahl des Bundeslandes richten.

**Comment by TetianaProkhorova** [comment]
70% fertig

**Comment by TetianaProkhorova** [comment]
100% fertig.
