### ISSUE TITLE
Exchanges definieren im GameCenterHelper

### ISSUE THREAD

**Issue by Simongotnews** [Simongotnews/SWP2#48]
AZ geschätzt: 6h+6h+3h (3 Personen) = 15h
AZ tatsächlich:

**Comment by Skeltek** [comment]
90% fertig

**Comment by Skeltek** [comment]
Die eigentlichen Exchanges zu definieren ging schnell, die Voraussetzungen zum Testen dieser zu schaffen dauerte eine Ewigkeit.
