### ISSUE TITLE
Shop-Button inkl. neue Scene

### ISSUE THREAD

**Issue by Simongotnews** [Simongotnews/SWP2#49]
AZ: 8h
(z.B. Einheiten kaufen mit dem Geld, das man hat (Geld wird generiert durch Bundesländer). Anzeige der eigenen Bundesländer in Dropdown-Menü. Dann kauf, dann einsetzen der gekauften Einheiten & Zuweisung auf das erhaltende Bundesland (ebenfalls durch Dropdown-Menü).

**Comment by Simongotnews** [comment]
(z.B. Einheiten kaufen mit dem Geld das man hat (Geld wird generiert durch Bundesländer). Anzeige der eigenen Bundesländer in Dropdown menü. Dann kauf, dann einsetzen der gekauften Einheiten & Zuweisung auf das erhaltende Bundesland (ebenfalls durch Dropdown-Menü). Wenn Fragen -> Slack..

**Comment by ILoveEduroam** [comment]
50% fertig
AZ bisher: 5,5 h

**Comment by ILoveEduroam** [comment]
100 %
AZ: 15,5 h
