### ISSUE TITLE
Bugfix Multiplayer

### ISSUE THREAD

**Issue by LeDaspien** [Simongotnews/SWP2#55]

**Comment by Skeltek** [comment]
Hier steht nicht drin welcher Bug gemeint ist.

**Comment by Skeltek** [comment]
30% fertig

**Comment by Skeltek** [comment]
Kritischen Fehler entdeckt, schwer zu finden. Gewünschte Funktionalität, Dokumentation und Quellen der 'player(receivedReplies)' Methode stimmen nicht mit Funktionalität in GKTurnBasedPlayer-Listenern überein.
Möglicherweise anderweitige Einstellung welche fehlt, aber extrem unwahrscheinlich. Vermutlich wird Workaround benötigt.
