### ISSUE TITLE
BL Einwohner verteilen

### ISSUE THREAD

**Issue by LeDaspien** [Simongotnews/SWP2#62]
Die Bundesländer sollen jeweils eine Truppenstärke erhalten, welche sich nach der Einwohnerzahl des Bundeslands richtet und noch mit einem zufälligen Wert faktorisiert werden.
Für die Zufallsverteilung soll ein Algorithmus entwickelt werden, welcher die Verteilung der Bundesländer und der Truppenstärke möglichst fair macht. Einwohner verteilen als Methode! wegen Game Center

**Comment by SimoneAtSWP2** [comment]
2 h

**Comment by SimoneAtSWP2** [comment]
weitere 10 h für Fairness-Umverteilung
