### ISSUE TITLE
Multiplayer Bug: Pfeil ziehen (Gamecenter) -> Spieler wird nicht richtig erkannt

### ISSUE THREAD

**Issue by LeDaspien** [Simongotnews/SWP2#65]

**Comment by Skeltek** [comment]
100% fertig

**Comment by Skeltek** [comment]
Nebenbei noch Routine optimiert und komplett auf CGFloat umgestellt. 'Laggigkeit' und störrisches Verhalten beseitigt und Auf Geschwindigkeit getrimmt.

**Comment by Skeltek** [comment]
Wurf ist jetzt auch in andere Richtung möglich mit korrekter Winkelberechnung, falls man später dazu neigt Wind über Modifikation des Gravitationsvektors zu implementieren.
