### ISSUE TITLE
Pfeil für Einstellung des Winkels

### ISSUE THREAD

**Issue by TobiasGit** [Simongotnews/SWP2#8]
AZ: 16h. Es soll der Pfeil für die Einstellung des Winkels beim Werfen erstellt werden, wenn ein Spieler wirft. Dieser soll unten an einer Stelle fixiert sein und an der Pfeilspitze frei nach unten und oben beweglich sein

**Comment by Simongotnews** [comment]
Pfeilgrafik in Krita erstellt und in Slack gepostet
