### ISSUE TITLE
Bugfix: Angreifer soll immer links sein

### ISSUE THREAD

**Issue by Simongotnews** [Simongotnews/SWP2#87]
Player 1 soll immer der eigene Spieler sein.

**Comment by Skeltek** [comment]
Done, gameScene hatte bei Neuaufruf die DummyIDs nicht neu gesetzt

**Comment by Skeltek** [comment]
Geschätzter Aufwand: 4-6 Stunden, tatsächlicher Aufwand: 3 Stunden
