### ISSUE TITLE
Datenaustausch beim Multiplayer

### ISSUE THREAD

**Issue by TobiasGit** [Simongotnews/SWP2#9]
AZ: 3 Personen à 4h. Es soll sich damit beschäftigt werden, wie der Datenaustausch beim Game Center funktioniert. Am besten sollte schon ein generischer Code für den Prototyp geschrieben werden, wie man den Multiplayer (Kampf zwischen 2 Bundesländern) realisieren kann ODER ob erst einmal ein lokaler Multiplayer einfacher wäre

**Comment by Skeltek** [comment]
#9 Laut Aufgabenbeschreibung zu 100% erledigt. Für weiteres zu Datenaustausch neues Ticket öffnen.
