### ISSUE TITLE
iTunes Connect Informationen sammeln & nötige Daten zusammentragen

### ISSUE THREAD

**Issue by Simongotnews** [Simongotnews/SWP2#91]
Alle nötigen Vorbereitungen treffen (zB. Texte verfassen ) damit am Montag die Übermittlung gut funktioniert.

**Comment by Simongotnews** [comment]
Guten, zusammenfassenden Artikel gefunden: https://www.ralfebert.de/ios/app-store-distribution/

**Comment by Simongotnews** [comment]
Durchgelesen bzw. Überflogen was alles erstellt werden muss. 
ca. 40% Abgeschlossen

**Comment by LeDaspien** [comment]
ca 60% nötigen Infos gefunden
https://hosting.1und1.de/digitalguide/websites/web-entwicklung/die-eigene-app-entwickeln-eine-ios-app-veroeffentlichen/
Artikel mit Infos
